language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(normpath(Base.find_package("CovarianceMatrices"), "..", "..")); using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(normpath(Base.find_package("CovarianceMatrices"), "..", "..")); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
